# employee_analysis.py
# Author: Raghul Gnanasekaran
# Email: 23f2002365@ds.study.iitm.ac.in

import pandas as pd
import matplotlib.pyplot as plt

# --------------------------
# Step 1: Load Employee Data
# --------------------------
# (In practice, replace this with pd.read_csv("employee_data.csv"))
data = {
    "EmployeeID": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Department": ["HR", "Engineering", "HR", "Sales", "Engineering", "Marketing", "HR", "Sales", "Engineering", "HR"],
    "Region": ["East", "West", "East", "North", "South", "East", "West", "South", "North", "East"],
    "PerformanceScore": [85, 90, 70, 88, 95, 78, 80, 92, 89, 77]
}

df = pd.DataFrame(data)

# ------------------------------
# Step 2: Calculate HR Frequency
# ------------------------------
hr_count = df[df["Department"] == "HR"].shape[0]
print(f"Frequency count of HR department: {hr_count}")

# --------------------------------------
# Step 3: Create Histogram of Departments
# --------------------------------------
plt.figure(figsize=(8, 5))
df["Department"].value_counts().plot(kind="bar", color="skyblue", edgecolor="black")

plt.title("Employee Distribution by Department (Sample)", fontsize=14)
plt.xlabel("Department")
plt.ylabel("Number of Employees")
plt.xticks(rotation=45)
plt.grid(axis="y", linestyle="--", alpha=0.7)

# Save as image
plt.tight_layout()
plt.savefig("department_distribution.png", dpi=300)

# --------------------------
# Step 4: Export as HTML
# --------------------------
html_content = f"""
<html>
<head>
<title>Employee Performance Analysis</title>
</head>
<body>
<h1>Employee Performance Visualization</h1>
<p><b>Frequency count of HR department:</b> {hr_count}</p>
<img src="department_distribution.png" alt="Department Distribution">
<p><i>Generated by Raghul Gnanasekaran (23f2002365@ds.study.iitm.ac.in)</i></p>
</body>
</html>
"""

with open("employee_analysis.html", "w") as f:
    f.write(html_content)

print("✅ Analysis complete. Files generated: department_distribution.png, employee_analysis.html")
